### ISSUE TITLE
[view] myinfo_setting

### ISSUE THREAD

**Issue by koda93** [choiyk/Itda#3]
- 정보 수정 페이지 들어갈 때 선택한 학과로 출력
- form validation에 맞으면 [정보 수정] 대화상자 후 mypage로 
아니면 redirection후 validation message 출력

**Comment by choiyk** [comment]
- form validation에 맞으면 [정보 수정] 대화상자 후 mypage로
아니면 redirection후 validation message 출력

contorller에서 alert 창을 출력하도록 alert.jsp 파일 구현
*alert창에서 확인 버튼을 누른 후 page redirect 됨 

사용법
model.addAttribute("msg", "정보가 변경되었습니다.");
model.addAttribute("url", "mypage");
return "redirect";

**Comment by koda93** [comment]
[정보 수정 페이지 들어갈 때 선택한 학과로 출력] 수정 완료했습니다
