### ISSUE TITLE
[Mapper] Articles 조회 문제

### ISSUE THREAD

**Issue by koda93** [choiyk/Itda#6]
meetingController의 meeting 메인 페이지를 출력하는 meeting(get) 컨트롤러에서
모임에 등록된 글을 조회하기 위한 부분 중 Line 53 부분

```java
List<ArticlesByMeeting> list = boardService.boardArticles(meeting.getId());
```

- BoardService의 boardArticles
- BoardMapper의 boardArticles

전부 체크 해봤지만 mapper의 `boardArticles`부터 제대로 동작하지 않는 것 같음
현재 meeting 뷰에서는 작성된 글 갯수만큼 \<div\>는 출력되지만 내용은 제대로 출력되지 않음

**Comment by choiyk** [comment]
dto의 getter, setter 의 이름과 mapper 쿼리 실행 결과의 칼럼명이 같아야 함
